# Generated by Django 3.2.19 on 2023-06-10 21:41

from django.db import migrations, models

import mailing_list.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_alter_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[(mailing_list.models.StatusChoice['success'], 'Success'), (mailing_list.models.StatusChoice['failed'], 'Failed'), (mailing_list.models.StatusChoice['pending'], 'Pending')], default='Pending', max_length=10),
        ),
    ]
