# Generated by Django 3.2.19 on 2023-06-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0003_alter_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mailing_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_list', to='mailing_list.mailinglist', verbose_name='Mailing list'),
        ),
    ]
